export enum ERRORS {
  TOKEN_EXPIRED = 'Token expired',
  BAD_TOKEN = 'Bad token',

  USER_NOT_FOUND = 'User not found',
  USER_REQUIRED_FIELDS = 'Email, username, and password are required',
  NOT_LOGGED_IN = 'You are not logged in',
  DUPLICATE_EMAIL = 'An account with this email already exists',
  NOT_ADMIN = 'You are not an admin',
  NOT_AUTHORIZED = 'You are not authorized to perform this action',
  Course_Required_Failed = 'Course Request Failed',
  Course_Not_Found = 'Course Not Found',
  Course_ID_MISSING = 'Course IDMISSING',
  Fields_ARE_MISSING = 'Fields ARE MISSING',
  Chapter_ID_MISSING = 'Chapter ID MISSING',
  Chapter_Not_Found = 'Chapter Not Found',
  Video_ID_MISSING = 'Video ID MISSING',
  Video_Not_Found = 'Video Not Found',
  NOT_SUBSCRIBED = 'You are not Subscribed',
}
